### ISSUE TITLE
styling is not working. fix it!

### ISSUE THREAD

**Issue by Ujjwal-soni98** [Ujjwal-soni98/ms_clone#2]

**Comment by smitioswal** [comment]
Can you please assign me this?

**Comment by Vipdhruvkalra** [comment]
Please explain what do u mean by this

**Comment by KushagraVarshney05** [comment]
@Ujjwal-soni98 i want to fix can you assign it to me...

**Comment by Ujjwal-soni98** [comment]
> Please explain what do u mean by this

@Vipdhruvkalra styling added in the css file is not working.
